"""Add is_admin

Revision ID: 5f1e00a37344
Revises: 6e1bb524b639
Create Date: 2025-10-09 10:17:39.454482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f1e00a37344"
down_revision: Union[str, Sequence[str], None] = "6e1bb524b639"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM reviews")
    op.execute("DELETE FROM products")
    op.execute("DELETE FROM users")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
