"""Add user model

Revision ID: db4fc8a485c8
Revises: 469e5e48177b
Create Date: 2025-10-02 16:22:40.537086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db4fc8a485c8"
down_revision: Union[str, Sequence[str], None] = "469e5e48177b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM products")
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.add_column("products", sa.Column("seller_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "products", "users", ["seller_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "seller_id")
    op.drop_table("users")
    # ### end Alembic commands ###
