"""Add review model

Revision ID: f02bd87fe1a1
Revises: db4fc8a485c8
Create Date: 2025-10-08 09:27:02.904207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f02bd87fe1a1"
down_revision: Union[str, Sequence[str], None] = "db4fc8a485c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM products")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("rating", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "rating")
    # ### end Alembic commands ###
